name: Node CI

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - "*"
env:
  CI: true
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}
#  NODE_ENV: test

jobs:
  pipeline:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: ['12.x', '14.x', '16.x']
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm install
        id: install

      - name: Install project dependencies
        run: npm run test
        id: test
  
      - name: Install project dependencies
        run: npm run browser-tests
        id: browser
 
      - name: Install project dependencies
        run: npm run lint
        id: lint
